/***********************************************************************
	- 제     목: 01_정보추출쿼리_FNAME_CNAME_삭제대상까지전부검출가능
	- 최초작성일: 2024-07-09
	- 최초작성자: 최명원
	- 최종수정일: 2025-07-18
	- 최종작성자: 최명원
************************************************************************/

-- FNAME 검출 // ERR_CODE 여부와 상관없이 검출 가능
SELECT A.POI_ID, F.N_NAME AS FNAME, C.CA_NAME, C.CB_NAME, C.CC_NAME, C.CD_NAME, D.ADDRESS, D.SAN, D.JIBUN_M, D.JIBUN_S
FROM PTM_COMMON A, PTC_POI_CLASS B, PTC_CLASS C, PTN_ADDR D, PTD_NAME E, PTN_NAME F
WHERE A.POI_ID = B.POI_ID
AND B.CLASS_CODE = C.CLASS_CODE
AND A.POI_ID = D.POI_ID
AND A.POI_ID = E.POI_ID
AND E.NAME_SEQ = F.NAME_SEQ
AND E.NAME_KIND = 0
AND A.POI_ID IN
(

)

-- CNAME 검출 // ERR_CODE 여부와 상관없이 검출 가능
SELECT A.POI_ID, F.N_NAME AS CNAME, C.CA_NAME, C.CB_NAME, C.CC_NAME, C.CD_NAME, D.ADDRESS, D.SAN, D.JIBUN_M, D.JIBUN_S
FROM PTM_COMMON A, PTC_POI_CLASS B, PTC_CLASS C, PTN_ADDR D, PTD_NAME E, PTN_NAME F
WHERE A.POI_ID = B.POI_ID
AND B.CLASS_CODE = C.CLASS_CODE
AND A.POI_ID = D.POI_ID
AND A.POI_ID = E.POI_ID
AND E.NAME_SEQ = F.NAME_SEQ
AND E.NAME_KIND = 1
AND A.POI_ID IN
(

)

-- 좌표를 원하는 경우 // GRS 기준 중심좌표 추출 , 삭제대상은 검출되지 않음
USE POI_MAIN_PRACT

SELECT E.MAP_ID, A.POI_ID, A.FNAME, A.CNAME, B.CLASS_CODE, C.CA_NAME, C.CB_NAME, C.CC_NAME, C.CD_NAME, F.LON, F.LAT
FROM vPOI_I_COMMON_ALL_GRS A, PTC_POI_CLASS B, PTC_CLASS C, PTN_ADDR D, POI_MAIN_ETC..[22y_2150_INDEX_220401] E, vobn_PTN_POI_XY_GRS F
WHERE A.POI_ID = B.POI_ID AND B.CLASS_CODE = C.CLASS_CODE AND A.POI_ID = D.POI_ID AND A.POI_ID = F.POI_ID
AND LEFT(A.TILE_ID,4) = E.MAP_ID
AND E.관할업체 = '티아이랩'
AND E.MAP_ID IN ()
AND F.XY_KIND = 0
ORDER BY E.MAP_ID, A.POI_ID

-- 주로 사용하는 쿼리 // GRS 기준 중심좌표 추출 , 삭제대상은 검출되지 않음
USE POI_MAIN_PRACT

SELECT E.MAP_ID, A.POI_ID, A.FNAME, A.CNAME, A.SNAME, B.CLASS_CODE, C.CA_NAME, C.CB_NAME, C.CC_NAME, C.CD_NAME, F.COMMENT, F.USER_NAME,
A.ADDR +' '+ CAST(A.PRIMARY_BUN AS varchar(10)) + '-' + CAST(A.SECONDARY_BUN AS varchar(10))
FROM vPOI_I_COMMON_ALL_GRS A, PTC_POI_CLASS B, PTC_CLASS C, PTN_ADDR D, POI_MAIN_ETC..[22y_2150_INDEX_220401] E, PTN_WORK_COMMENT F
WHERE A.POI_ID = B.POI_ID AND B.CLASS_CODE = C.CLASS_CODE AND A.POI_ID = D.POI_ID AND A.POI_ID = F.POI_ID
AND LEFT(A.TILE_ID,4) = E.MAP_ID
AND E.관할업체 = '티아이랩'
AND A.FNAME LIKE '%%'
ORDER BY E.MAP_ID, A.POI_ID

SELECT DISTINCT E.MAP_ID, A.POI_ID, A.FNAME, A.CNAME, A.SNAME,
-- B.CLASS_CODE, C.CA_NAME, C.CB_NAME, C.CC_NAME, C.CD_NAME,
-- A.ADDR, A.SAN_BUN, A.PRIMARY_BUN, A.SECONDARY_BUN,
A.ADDR +' '+ CAST(A.PRIMARY_BUN AS varchar(10)) + '-' + CAST(A.SECONDARY_BUN AS varchar(10)) AS 구주소,
F.ADDRESS +' '+ CAST(F.BULD_MNNM AS varchar(10)) + '-' + CAST(F.BULD_SLNO AS varchar(10)) AS 새주소,
A.TELE_A + '-' +  A.TELE_B + '-' +  A.TELE_C AS 전화번호
FROM vPOI_I_COMMON_ALL_GRS A, PTC_POI_CLASS B, PTC_CLASS C, PTN_ADDR D, POI_MAIN_ETC..[22y_2150_INDEX_220401] E, PTN_ROAD_ADDR F
WHERE A.POI_ID = B.POI_ID
AND B.CLASS_CODE = C.CLASS_CODE
AND A.POI_ID = D.POI_ID
AND LEFT(A.TILE_ID,4) = E.MAP_ID
AND A.POI_ID = F.POI_ID
AND E.관할업체 = '티아이랩'
ORDER BY E.MAP_ID, A.POI_ID

/*중심좌표*/
select XY_GRS.STX as grs_x, XY_GRS.STY as grs_y 
from PTN_POI_XY
where XY_KIND = 0 and poi_id = 

select XY_BESSEL.STX as bes_x, XY_BESSEL.STY  as bes_y 
from PTN_POI_XY
where XY_KIND = 0 and poi_id = 

/*안내좌표*/
select XY_GRS.STX as grs_x, XY_GRS.STY as grs_y 
from PTN_POI_XY
where XY_KIND = 1 and poi_id = 

select XY_BESSEL.STX as bes_x, XY_BESSEL.STY  as bes_y 
from PTN_POI_XY
where XY_KIND = 1 and poi_id = 

