/***********************************************************************
	- 제     목: 01_정보추출쿼리_FNAME_CNAME_삭제대상까지전부검출가능
	- 최초작성일: 2024-07-09
	- 최초작성자: 최명원
	- 최종수정일: 2025-07-18
	- 최종작성자: 최명원
************************************************************************/

-- FNAME 검출 // ERR_CODE 여부와 상관없이 검출 가능
SELECT 
      A.POI_ID
    , F.N_NAME AS FNAME
    , C.CA_NAME
    , C.CB_NAME
    , C.CC_NAME
    , C.CD_NAME
    , D.ADDRESS
    , D.SAN
    , D.JIBUN_M
    , D.JIBUN_S
FROM PTM_COMMON AS A WITH (NOLOCK)
INNER JOIN PTC_POI_CLASS AS B WITH (NOLOCK) 
    ON A.POI_ID = B.POI_ID
INNER JOIN PTC_CLASS AS C WITH (NOLOCK) 
    ON B.CLASS_CODE = C.CLASS_CODE
INNER JOIN PTN_ADDR AS D WITH (NOLOCK) 
    ON A.POI_ID = D.POI_ID
INNER JOIN PTD_NAME AS E WITH (NOLOCK) 
    ON A.POI_ID = E.POI_ID
INNER JOIN PTN_NAME AS F WITH (NOLOCK) 
    ON E.NAME_SEQ = F.NAME_SEQ
WHERE E.NAME_KIND = 0  -- 0: FNAME 필터
  AND A.POI_ID IN () -- 추출 대상 ID 입력

-- 좌표를 원하는 경우 // GRS 기준 중심좌표 추출 , 삭제대상은 검출되지 않음
USE POI_MAIN_PRACT;
GO

SELECT 
      E.MAP_ID
    , A.POI_ID
    , A.FNAME
    , A.CNAME
    , B.CLASS_CODE
    , C.CA_NAME, C.CB_NAME, C.CC_NAME, C.CD_NAME
    , F.LON
    , F.LAT
FROM POI_MAIN_ETC..[22y_2150_INDEX_220401] AS E WITH (NOLOCK)
INNER JOIN vPOI_I_COMMON_ALL_GRS AS A WITH (NOLOCK) 
    ON LEFT(A.TILE_ID, 4) = E.MAP_ID
INNER JOIN PTC_POI_CLASS AS B WITH (NOLOCK) 
    ON A.POI_ID = B.POI_ID
INNER JOIN PTC_CLASS AS C WITH (NOLOCK) 
    ON B.CLASS_CODE = C.CLASS_CODE
INNER JOIN PTN_ADDR AS D WITH (NOLOCK) 
    ON A.POI_ID = D.POI_ID
INNER JOIN vobn_PTN_POI_XY_GRS AS F WITH (NOLOCK) 
    ON A.POI_ID = F.POI_ID
WHERE E.관할업체 = '티아이랩'
  AND E.MAP_ID IN ( )
  AND F.XY_KIND = 0
ORDER BY E.MAP_ID, A.POI_ID;

-- 주로 사용하는 쿼리 // GRS 기준 중심좌표 추출 , 삭제대상은 검출되지 않음
USE POI_MAIN_PRACT;
GO

-- 1) 작업 코멘트 포함 상세 조회
SELECT 
      E.MAP_ID
    , A.POI_ID
    , A.FNAME, A.CNAME, A.SNAME
    , B.CLASS_CODE
    , C.CA_NAME, C.CB_NAME, C.CC_NAME, C.CD_NAME
    , F.COMMENT
    , F.USER_NAME
    , CONCAT(A.ADDR, ' ', A.PRIMARY_BUN, '-', A.SECONDARY_BUN) AS [Full_Address]
FROM vPOI_I_COMMON_ALL_GRS AS A WITH (NOLOCK)
INNER JOIN PTC_POI_CLASS AS B   WITH (NOLOCK) ON A.POI_ID = B.POI_ID
INNER JOIN PTC_CLASS AS C       WITH (NOLOCK) ON B.CLASS_CODE = C.CLASS_CODE
INNER JOIN PTN_ADDR AS D        WITH (NOLOCK) ON A.POI_ID = D.POI_ID
INNER JOIN PTN_WORK_COMMENT AS F WITH (NOLOCK) ON A.POI_ID = F.POI_ID
INNER JOIN POI_MAIN_ETC..[22y_2150_INDEX_220401] AS E ON LEFT(A.TILE_ID, 4) = E.MAP_ID
WHERE E.관할업체 = '티아이랩'
  AND A.FNAME LIKE '%' -- 실제 검색어 입력 시 인덱스 고려
ORDER BY E.MAP_ID, A.POI_ID;


-- 2) 구주소/새주소/전화번호 통합 조회 (DISTINCT 포함)
SELECT DISTINCT 
      E.MAP_ID
    , A.POI_ID
    , A.FNAME, A.CNAME, A.SNAME
    , CONCAT(A.ADDR, ' ', A.PRIMARY_BUN, '-', A.SECONDARY_BUN) AS 구주소
    , CONCAT(F.ADDRESS, ' ', F.BULD_MNNM, '-', F.BULD_SLNO) AS 새주소
    , CONCAT_WS('-', NULLIF(A.TELE_A, ''), NULLIF(A.TELE_B, ''), NULLIF(A.TELE_C, '')) AS 전화번호
FROM vPOI_I_COMMON_ALL_GRS AS A WITH (NOLOCK)
INNER JOIN PTC_POI_CLASS AS B   WITH (NOLOCK) ON A.POI_ID = B.POI_ID
INNER JOIN PTC_CLASS AS C       WITH (NOLOCK) ON B.CLASS_CODE = C.CLASS_CODE
INNER JOIN PTN_ADDR AS D        WITH (NOLOCK) ON A.POI_ID = D.POI_ID
INNER JOIN PTN_ROAD_ADDR AS F   WITH (NOLOCK) ON A.POI_ID = F.POI_ID
INNER JOIN POI_MAIN_ETC..[22y_2150_INDEX_220401] AS E ON LEFT(A.TILE_ID, 4) = E.MAP_ID
WHERE E.관할업체 = '티아이랩'
ORDER BY E.MAP_ID, A.POI_ID;

/*중심좌표*/
SELECT XY_GRS.STX AS grs_x, XY_GRS.STY AS grs_y 
FROM PTN_POI_XY
WHERE XY_KIND = 0 AND POI_ID = 

SELECT XY_BESSEL.STX AS bes_x, XY_BESSEL.STY  AS bes_y 
FROM PTN_POI_XY
WHERE XY_KIND = 0 AND POI_ID = 

/*안내좌표*/
SELECT XY_GRS.STX AS grs_x, XY_GRS.STY AS grs_y 
FROM PTN_POI_XY
WHERE XY_KIND = 1 AND POI_ID = 
	
SELECT XY_BESSEL.STX AS bes_x, XY_BESSEL.STY  AS bes_y 
FROM PTN_POI_XY
WHERE XY_KIND = 1 AND POI_ID =  

