/**************************************
	- 제     목: 공사중 POI 추출 쿼리
	- 최초작성일: 2024-04-17
	- 최초작성자: 최명원
****************************************/

USE POI_MAIN_PRACT;
GO

SELECT DISTINCT 
      A.POI_ID, A.UPDATE_DATE, C.CC_NAME, E.N_NAME AS 명칭
    , G.USER_NAME, H.CONSTRUCT_DATE, H.MEMO, A.ERR_CODE
FROM PTM_COMMON AS A WITH (NOLOCK)
INNER JOIN PTC_POI_CLASS AS B WITH (NOLOCK) ON A.POI_ID = B.POI_ID
INNER JOIN PTC_CLASS AS C     WITH (NOLOCK) ON B.CLASS_CODE = C.CLASS_CODE
INNER JOIN PTD_NAME AS D      WITH (NOLOCK) ON A.POI_ID = D.POI_ID
INNER JOIN PTN_NAME AS E      WITH (NOLOCK) ON D.NAME_SEQ = E.NAME_SEQ
INNER JOIN PTN_CONSTRUCT AS H WITH (NOLOCK) ON A.POI_ID = H.POI_ID
INNER JOIN GTN_USER AS G      WITH (NOLOCK) ON H.USER_SEQ = G.USER_SEQ
INNER JOIN PTN_TELEPHONE AS F WITH (NOLOCK) ON A.POI_ID = F.POI_ID
INNER JOIN POI_MAIN_ETC..[22y_2150_INDEX_220401] AS X 
    ON LEFT(A.TILE_ID, 4) =  X.MAP_ID 
WHERE D.NAME_KIND = 0
  AND X.관할업체 = N'티아이랩'
  AND A.ERR_CODE NOT IN (4, 260, 516)
ORDER BY H.CONSTRUCT_DATE;
