/***********************************************************************
	- 제     목: 22_현대기아_판매점_수리점추출쿼리
	- 최초작성일: 
	- 최초작성자: 
	- 최종수정일: 
	- 최종작성자: 
************************************************************************/
USE POI_MAIN_PRACT

/* 현대자동차 기아자동차 */
SELECT DISTINCT A.TELE_A + '-' +  A.TELE_B + '-' +  A.TELE_C AS TELE,
A.POI_ID, REPLACE(A.FNAME,'/','') AS FNAME, REPLACE(A.CNAME,'/','') AS CNAME, REPLACE(A.FNAME,'/','') + REPLACE(A.CNAME,'/','') AS 명칭,
-- B.CLASS_CODE, C.CA_NAME, C.CB_NAME, C.CC_NAME, C.CD_NAME,
-- A.ADDR, A.SAN_BUN, A.PRIMARY_BUN, A.SECONDARY_BUN,
A.ADDR +' '+ CAST(A.PRIMARY_BUN AS varchar(10)) + '-' + CAST(A.SECONDARY_BUN AS varchar(10)) AS 구주소,
F.ADDRESS +' '+ CAST(F.BULD_MNNM AS varchar(10)) + '-' + CAST(F.BULD_SLNO AS varchar(10)) AS 새주소,
B.CLASS_CODE
FROM vPOI_I_COMMON_ALL_GRS A, PTC_POI_CLASS B, PTC_CLASS C, PTN_ADDR D, POI_MAIN_ETC..[22y_2150_INDEX_220401] E, PTN_ROAD_ADDR F
WHERE A.POI_ID = B.POI_ID
AND B.CLASS_CODE = C.CLASS_CODE
AND A.POI_ID = D.POI_ID
AND LEFT(A.TILE_ID,4) = E.MAP_ID
AND A.POI_ID = F.POI_ID
AND E.관할업체 = '티아이랩'
AND B.CLASS_CODE IN ('01020501','01020502')
ORDER BY B.CLASS_CODE


/* 현대블루핸즈 기아오토큐 */
SELECT DISTINCT A.TELE_A + '-' +  A.TELE_B + '-' +  A.TELE_C AS TELE,
A.POI_ID, REPLACE(A.FNAME,'/','') AS FNAME, REPLACE(REPLACE(REPLACE(REPLACE(A.CNAME,'/',''),'(',''),')',''),'부분정비','') AS CNAME,
REPLACE(A.FNAME,'/','') + REPLACE(REPLACE(REPLACE(REPLACE(A.CNAME,'/',''),'(',''),')',''),'부분정비','') AS 명칭,
-- B.CLASS_CODE, C.CA_NAME, C.CB_NAME, C.CC_NAME, C.CD_NAME,
-- A.ADDR, A.SAN_BUN, A.PRIMARY_BUN, A.SECONDARY_BUN,
A.ADDR +' '+ CAST(A.PRIMARY_BUN AS varchar(10)) + '-' + CAST(A.SECONDARY_BUN AS varchar(10)) AS 구주소,
F.ADDRESS +' '+ CAST(F.BULD_MNNM AS varchar(10)) + '-' + CAST(F.BULD_SLNO AS varchar(10)) AS 새주소,
B.CLASS_CODE
FROM vPOI_I_COMMON_ALL_GRS A, PTC_POI_CLASS B, PTC_CLASS C, PTN_ADDR D, POI_MAIN_ETC..[22y_2150_INDEX_220401] E, PTN_ROAD_ADDR F
WHERE A.POI_ID = B.POI_ID
AND B.CLASS_CODE = C.CLASS_CODE
AND A.POI_ID = D.POI_ID
AND LEFT(A.TILE_ID,4) = E.MAP_ID
AND A.POI_ID = F.POI_ID
AND E.관할업체 = '티아이랩'
AND B.CLASS_CODE IN ('01020704','01020709')
ORDER BY B.CLASS_CODE

/* 지정공장(현대블루핸즈) 지정공장(기아오토큐) */
SELECT DISTINCT A.TELE_A + '-' +  A.TELE_B + '-' +  A.TELE_C AS TELE,
A.POI_ID, REPLACE(A.FNAME,'/','') AS FNAME, REPLACE(REPLACE(REPLACE(REPLACE(A.CNAME,'/',''),'(',''),')',''),'지정공장정비','') AS CNAME,
REPLACE(A.FNAME,'/','') + REPLACE(REPLACE(REPLACE(REPLACE(A.CNAME,'/',''),'(',''),')',''),'지정공장정비','') AS 명칭,
-- B.CLASS_CODE, C.CA_NAME, C.CB_NAME, C.CC_NAME, C.CD_NAME,
-- A.ADDR, A.SAN_BUN, A.PRIMARY_BUN, A.SECONDARY_BUN,
A.ADDR +' '+ CAST(A.PRIMARY_BUN AS varchar(10)) + '-' + CAST(A.SECONDARY_BUN AS varchar(10)) AS 구주소,
F.ADDRESS +' '+ CAST(F.BULD_MNNM AS varchar(10)) + '-' + CAST(F.BULD_SLNO AS varchar(10)) AS 새주소,
B.CLASS_CODE
FROM vPOI_I_COMMON_ALL_GRS A, PTC_POI_CLASS B, PTC_CLASS C, PTN_ADDR D, POI_MAIN_ETC..[22y_2150_INDEX_220401] E, PTN_ROAD_ADDR F
WHERE A.POI_ID = B.POI_ID
AND B.CLASS_CODE = C.CLASS_CODE
AND A.POI_ID = D.POI_ID
AND LEFT(A.TILE_ID,4) = E.MAP_ID
AND A.POI_ID = F.POI_ID
AND E.관할업체 = '티아이랩'
AND B.CLASS_CODE IN ('01020701','01020711')
ORDER BY B.CLASS_CODE

/* 기아(오토큐) */
SELECT DISTINCT A.TELE_A + '-' +  A.TELE_B + '-' +  A.TELE_C AS TELE,
A.POI_ID, REPLACE(A.FNAME,'/','') AS FNAME, REPLACE(REPLACE(REPLACE(REPLACE(A.CNAME,'/',''),'(',''),')',''),'직영정비','') AS CNAME,
REPLACE(A.FNAME,'/','') + REPLACE(REPLACE(REPLACE(REPLACE(A.CNAME,'/',''),'(',''),')',''),'직영정비','') AS 명칭,
-- B.CLASS_CODE, C.CA_NAME, C.CB_NAME, C.CC_NAME, C.CD_NAME,
-- A.ADDR, A.SAN_BUN, A.PRIMARY_BUN, A.SECONDARY_BUN,
A.ADDR +' '+ CAST(A.PRIMARY_BUN AS varchar(10)) + '-' + CAST(A.SECONDARY_BUN AS varchar(10)) AS 구주소,
F.ADDRESS +' '+ CAST(F.BULD_MNNM AS varchar(10)) + '-' + CAST(F.BULD_SLNO AS varchar(10)) AS 새주소,
B.CLASS_CODE
FROM vPOI_I_COMMON_ALL_GRS A, PTC_POI_CLASS B, PTC_CLASS C, PTN_ADDR D, POI_MAIN_ETC..[22y_2150_INDEX_220401] E, PTN_ROAD_ADDR F
WHERE A.POI_ID = B.POI_ID
AND B.CLASS_CODE = C.CLASS_CODE
AND A.POI_ID = D.POI_ID
AND LEFT(A.TILE_ID,4) = E.MAP_ID
AND A.POI_ID = F.POI_ID
AND E.관할업체 = '티아이랩'
AND B.CLASS_CODE IN ('01020602')
ORDER BY B.CLASS_CODE

/* 지정공장(상용블루핸즈) 지정공장(상용오토큐) */
SELECT DISTINCT A.TELE_A + '-' +  A.TELE_B + '-' +  A.TELE_C AS TELE,
A.POI_ID,
REPLACE(REPLACE(A.FNAME ,'[상용]',''),'/','') AS FNAME,
REPLACE(REPLACE(REPLACE(REPLACE(A.CNAME,'/',''),'(',''),')',''),'지정공장정비','') AS CNAME,
REPLACE(REPLACE(A.FNAME ,'[상용]',''),'/','') + REPLACE(REPLACE(REPLACE(REPLACE(A.CNAME,'/',''),'(',''),')',''),'지정공장정비','')  AS 명칭,
-- B.CLASS_CODE, C.CA_NAME, C.CB_NAME, C.CC_NAME, C.CD_NAME,
-- A.ADDR, A.SAN_BUN, A.PRIMARY_BUN, A.SECONDARY_BUN,
A.ADDR +' '+ CAST(A.PRIMARY_BUN AS varchar(10)) + '-' + CAST(A.SECONDARY_BUN AS varchar(10)) AS 구주소,
F.ADDRESS +' '+ CAST(F.BULD_MNNM AS varchar(10)) + '-' + CAST(F.BULD_SLNO AS varchar(10)) AS 새주소,
B.CLASS_CODE
FROM vPOI_I_COMMON_ALL_GRS A, PTC_POI_CLASS B, PTC_CLASS C, PTN_ADDR D, POI_MAIN_ETC..[22y_2150_INDEX_220401] E, PTN_ROAD_ADDR F
WHERE A.POI_ID = B.POI_ID
AND B.CLASS_CODE = C.CLASS_CODE
AND A.POI_ID = D.POI_ID
AND LEFT(A.TILE_ID,4) = E.MAP_ID
AND A.POI_ID = F.POI_ID
AND E.관할업체 = '티아이랩'
AND B.CLASS_CODE IN ('01020721','01020722')
ORDER BY B.CLASS_CODE