/***********************************************************************
	- 제     목: 22_현대기아_판매점_수리점추출쿼리
	- 최초작성일: 
	- 최초작성자: 
	- 최종수정일: 
	- 최종작성자: 
************************************************************************/
USE POI_MAIN_PRACT

/* 현대자동차 기아자동차 */
SELECT DISTINCT 
      -- 전화번호 결합: 하나라도 NULL이 있어도 안전하게 처리
      CONCAT_WS('-', NULLIF(A.TELE_A, ''), NULLIF(A.TELE_B, ''), NULLIF(A.TELE_C, '')) AS TELE
    , A.POI_ID
    -- 명칭 정화: REPLACE 중첩을 깔끔하게 정리
    , REPLACE(A.FNAME, '/', '') AS FNAME
    , REPLACE(A.CNAME, '/', '') AS CNAME
    , CONCAT(REPLACE(A.FNAME, '/', ''), REPLACE(A.CNAME, '/', '')) AS 명칭
    -- 주소 결합: CAST 없이 CONCAT으로 가독성 확보
    , CONCAT(A.ADDR, ' ', A.PRIMARY_BUN, '-', A.SECONDARY_BUN) AS 구주소
    , CONCAT(F.ADDRESS, ' ', F.BULD_MNNM, '-', F.BULD_SLNO) AS 새주소
    , B.CLASS_CODE
FROM vPOI_I_COMMON_ALL_GRS AS A WITH (NOLOCK)
INNER JOIN PTC_POI_CLASS AS B WITH (NOLOCK) ON A.POI_ID = B.POI_ID
INNER JOIN PTC_CLASS AS C     WITH (NOLOCK) ON B.CLASS_CODE = C.CLASS_CODE
INNER JOIN PTN_ADDR AS D      WITH (NOLOCK) ON A.POI_ID = D.POI_ID
INNER JOIN PTN_ROAD_ADDR AS F WITH (NOLOCK) ON A.POI_ID = F.POI_ID
INNER JOIN POI_MAIN_ETC..[22y_2150_INDEX_220401] AS E ON LEFT(A.TILE_ID, 4) = E.MAP_ID
WHERE E.관할업체 = '티아이랩'
  AND B.CLASS_CODE IN ('01020501', '01020502')
ORDER BY B.CLASS_CODE;


/* 현대블루핸즈 기아오토큐 */
SELECT DISTINCT 
      -- 전화번호: 데이터 유실 방지를 위해 CONCAT_WS 사용
      CONCAT_WS('-', NULLIF(A.TELE_A, ''), NULLIF(A.TELE_B, ''), NULLIF(A.TELE_C, '')) AS TELE
    , A.POI_ID
    -- FNAME: 슬래시 제거
    , REPLACE(A.FNAME, '/', '') AS FNAME
    -- CNAME: 불필요한 특수문자 및 '부분정비' 키워드 일괄 제거
    , REPLACE(REPLACE(REPLACE(REPLACE(A.CNAME, '/', ''), '(', ''), ')', ''), '부분정비', '') AS CNAME
    -- 명칭: 정화된 FNAME과 CNAME 결합
    , CONCAT(REPLACE(A.FNAME, '/', ''), REPLACE(REPLACE(REPLACE(REPLACE(A.CNAME, '/', ''), '(', ''), ')', ''), '부분정비', '')) AS 명칭
    -- 주소: CAST 연산 최소화 및 가독성 개선
    , CONCAT(A.ADDR, ' ', A.PRIMARY_BUN, '-', A.SECONDARY_BUN) AS 구주소
    , CONCAT(F.ADDRESS, ' ', F.BULD_MNNM, '-', F.BULD_SLNO) AS 새주소
    , B.CLASS_CODE
FROM vPOI_I_COMMON_ALL_GRS AS A WITH (NOLOCK)
INNER JOIN PTC_POI_CLASS AS B WITH (NOLOCK) ON A.POI_ID = B.POI_ID
INNER JOIN PTC_CLASS AS C     WITH (NOLOCK) ON B.CLASS_CODE = C.CLASS_CODE
INNER JOIN PTN_ADDR AS D      WITH (NOLOCK) ON A.POI_ID = D.POI_ID
INNER JOIN PTN_ROAD_ADDR AS F WITH (NOLOCK) ON A.POI_ID = F.POI_ID
-- LEFT 함수 대신 LIKE를 사용하여 TILE_ID 인덱스를 태움
INNER JOIN POI_MAIN_ETC..[22y_2150_INDEX_220401] AS E ON LEFT(A.TILE_ID, 4) = E.MAP_ID
WHERE E.관할업체 = '티아이랩'
  AND B.CLASS_CODE IN ('01020704', '01020709') 
ORDER BY B.CLASS_CODE;

/* 지정공장(현대블루핸즈) 지정공장(기아오토큐) */
SELECT DISTINCT 
      -- 전화번호: CONCAT_WS로 하이픈 연결 (NULL 발생 시에도 안전)
      CONCAT_WS('-', NULLIF(A.TELE_A, ''), NULLIF(A.TELE_B, ''), NULLIF(A.TELE_C, '')) AS TELE
    , A.POI_ID
    -- 명칭 정화: 슬래시, 괄호, '지정공장정비' 키워드 일괄 제거
    , REPLACE(A.FNAME, '/', '') AS FNAME
    , REPLACE(REPLACE(REPLACE(REPLACE(A.CNAME, '/', ''), '(', ''), ')', ''), '지정공장정비', '') AS CNAME
    , CONCAT(REPLACE(A.FNAME, '/', ''), REPLACE(REPLACE(REPLACE(REPLACE(A.CNAME, '/', ''), '(', ''), ')', ''), '지정공장정비', '')) AS 명칭
    -- 주소: 문자열 결합 최적화
    , CONCAT(A.ADDR, ' ', A.PRIMARY_BUN, '-', A.SECONDARY_BUN) AS 구주소
    , CONCAT(F.ADDRESS, ' ', F.BULD_MNNM, '-', F.BULD_SLNO) AS 새주소
    , B.CLASS_CODE
FROM vPOI_I_COMMON_ALL_GRS AS A WITH (NOLOCK)
INNER JOIN PTC_POI_CLASS AS B WITH (NOLOCK) ON A.POI_ID = B.POI_ID
INNER JOIN PTC_CLASS AS C     WITH (NOLOCK) ON B.CLASS_CODE = C.CLASS_CODE
INNER JOIN PTN_ADDR AS D      WITH (NOLOCK) ON A.POI_ID = D.POI_ID
INNER JOIN PTN_ROAD_ADDR AS F WITH (NOLOCK) ON A.POI_ID = F.POI_ID
INNER JOIN POI_MAIN_ETC..[22y_2150_INDEX_220401] AS E ON LEFT(A.TILE_ID,4 ) =E.MAP_ID
WHERE E.관할업체 = '티아이랩'
  AND B.CLASS_CODE IN ('01020701', '01020711')
ORDER BY B.CLASS_CODE;

/* 기아(오토큐) */
SELECT DISTINCT 
      -- 전화번호: 하나라도 비어있으면 빈 값 처리 (NULL 전파 방지)
      CONCAT_WS('-', NULLIF(A.TELE_A, ''), NULLIF(A.TELE_B, ''), NULLIF(A.TELE_C, '')) AS TELE
    , A.POI_ID
    , CL.FNAME_CLEAN AS FNAME
    , CL.CNAME_CLEAN AS CNAME
    , CONCAT(CL.FNAME_CLEAN, CL.CNAME_CLEAN) AS 명칭
    -- 주소 결합: CAST 없이 간결하게 처리
    , CONCAT(A.ADDR, ' ', A.PRIMARY_BUN, '-', A.SECONDARY_BUN) AS 구주소
    , CONCAT(F.ADDRESS, ' ', F.BULD_MNNM, '-', F.BULD_SLNO) AS 새주소
    , B.CLASS_CODE
FROM vPOI_I_COMMON_ALL_GRS AS A WITH (NOLOCK)
INNER JOIN PTC_POI_CLASS AS B WITH (NOLOCK) ON A.POI_ID = B.POI_ID
INNER JOIN PTC_CLASS AS C     WITH (NOLOCK) ON B.CLASS_CODE = C.CLASS_CODE
INNER JOIN PTN_ADDR AS D      WITH (NOLOCK) ON A.POI_ID = D.POI_ID
INNER JOIN PTN_ROAD_ADDR AS F WITH (NOLOCK) ON A.POI_ID = F.POI_ID
INNER JOIN POI_MAIN_ETC..[22y_2150_INDEX_220401] AS E ON LEFT(A.TILE_ID, 4) = E.MAP_ID
CROSS APPLY (
    SELECT 
        REPLACE(A.FNAME, '/', '') AS FNAME_CLEAN,
        REPLACE(REPLACE(REPLACE(REPLACE(A.CNAME, '/', ''), '(', ''), ')', ''), '직영정비', '') AS CNAME_CLEAN
) AS CL
WHERE E.관할업체 = '티아이랩'
  AND B.CLASS_CODE = '01020602'
ORDER BY B.CLASS_CODE;

/* 지정공장(상용블루핸즈) 지정공장(상용오토큐) */
SELECT DISTINCT 
      -- 전화번호: 하나라도 NULL이면 안전하게 빈 문자열 처리
      CONCAT_WS('-', NULLIF(A.TELE_A, ''), NULLIF(A.TELE_B, ''), NULLIF(A.TELE_C, '')) AS TELE
    , A.POI_ID
    , CL.FNAME_CLEAN AS FNAME
    , CL.CNAME_CLEAN AS CNAME
    , CONCAT(CL.FNAME_CLEAN, CL.CNAME_CLEAN) AS 명칭
    -- 주소: CAST 연산 생략 및 깔끔한 결합
    , CONCAT(A.ADDR, ' ', A.PRIMARY_BUN, '-', A.SECONDARY_BUN) AS 구주소
    , CONCAT(F.ADDRESS, ' ', F.BULD_MNNM, '-', F.BULD_SLNO) AS 새주소
    , B.CLASS_CODE
FROM vPOI_I_COMMON_ALL_GRS AS A WITH (NOLOCK)
INNER JOIN PTC_POI_CLASS AS B WITH (NOLOCK) ON A.POI_ID = B.POI_ID
INNER JOIN PTC_CLASS AS C     WITH (NOLOCK) ON B.CLASS_CODE = C.CLASS_CODE
INNER JOIN PTN_ADDR AS D      WITH (NOLOCK) ON A.POI_ID = D.POI_ID
INNER JOIN PTN_ROAD_ADDR AS F WITH (NOLOCK) ON A.POI_ID = F.POI_ID
INNER JOIN POI_MAIN_ETC..[22y_2150_INDEX_220401] AS E ON LEFT(A.TILE_ID, 4) = E.MAP_ID
CROSS APPLY (
    SELECT 
        REPLACE(REPLACE(A.FNAME, '[상용]', ''), '/', '') AS FNAME_CLEAN,
        REPLACE(REPLACE(REPLACE(REPLACE(A.CNAME, '/', ''), '(', ''), ')', ''), '지정공장정비', '') AS CNAME_CLEAN
) AS CL

WHERE E.관할업체 = '티아이랩'
  AND B.CLASS_CODE IN ('01020721', '01020722')
ORDER BY B.CLASS_CODE;
