/***********************************************************************
	- 제     목: 23_크롤링검출관련쿼리
	- 최초작성일: 2025-07-31
	- 최초작성자: 최명원
	- 최종수정일: 2025-08-01
	- 최종작성자: 최명원
************************************************************************/
USE POI_MAIN_PRACT

/* 원도 내 검출 쿼리 (일반) */
SELECT DISTINCT A.FNAME, A.CNAME, A.ADDR, A.ADDR2, A.PRIMARY_BUN, A.SECONDARY_BUN, A.SAN_BUN, A.IFLOOR, A.TELE_A, A.TELE_B, A.TELE_C,
B.ADDRESS, B.BULD_MNNM, B.BULD_SLNO
FROM vPOI_I_COMMON_ALL_GRS A, PTN_ROAD_ADDR B, PTC_POI_CLASS C, PTC_CLASS D
WHERE A.POI_ID = B.POI_ID
AND A.POI_ID = C.POI_ID
AND C.CLASS_CODE = D.CLASS_CODE
-- AND A.FNAME LIKE '%%'
-- AND C.CLASS_CODE = ''


/* 원도 내 검출 쿼리 (휴무일, 영업일, 운영시간) */
SELECT DISTINCT A.FNAME, A.CNAME, A.ADDR, A.ADDR2, A.PRIMARY_BUN, A.SECONDARY_BUN, A.SAN_BUN, A.IFLOOR, A.TELE_A, A.TELE_B, A.TELE_C,
B.ADDRESS, B.BULD_MNNM, B.BULD_SLNO,
E.WEEKDAY, E.ST_HOUR, E.ST_MIN, E.ED_HOUR, E.ED_MIN, '', '' ,'', F.DATE
FROM vPOI_I_COMMON_ALL_GRS A, PTN_ROAD_ADDR B, PTC_POI_CLASS C, PTC_CLASS D, PTN_WORK_HOUR_REGULAR E, PTN_OFFDAY_DATE F
WHERE A.POI_ID = B.POI_ID
AND A.POI_ID = C.POI_ID
AND C.CLASS_CODE = D.CLASS_CODE
AND A.POI_ID = E.POI_ID
AND A.POI_ID = F.POI_ID
-- AND A.FNAME LIKE '%%'
-- AND C.CLASS_CODE = ''

/* 원도 내 검출 쿼리 (입주일자) */
SELECT DISTINCT A.FNAME, A.CNAME, A.ADDR, A.ADDR2, A.PRIMARY_BUN, A.SECONDARY_BUN, A.SAN_BUN, A.IFLOOR, A.TELE_A, A.TELE_B, A.TELE_C,
B.ADDRESS, B.BULD_MNNM, B.BULD_SLNO, E.CONSTRUCT_DATE
FROM vPOI_I_COMMON_ALL_GRS A, PTN_ROAD_ADDR B, PTC_POI_CLASS C, PTC_CLASS D, PTN_CONSTRUCT E
WHERE A.POI_ID = B.POI_ID
AND A.POI_ID = C.POI_ID
AND C.CLASS_CODE = D.CLASS_CODE
AND A.POI_ID = E.POI_ID
-- AND A.FNAME LIKE '%%'
-- AND C.CLASS_CODE = ''