-- SQL_01 실습문제 1
USE CP_TILAB_NEW
SELECT BRAND, RAW_CNAME, RAW_ADDR, RAW_TEL
FROM FRAN_홈플러스익스프레스_230116

-- SQL_01 실습문제 2
USE CP_TILAB_NEW
SELECT *
FROM FRAN_홈플러스익스프레스_230116

-- SQL_02 실습문제 1
USE POI_MAIN_PRACT
SELECT *
FROM vPOI_I_COMMON_ALL_GRS
WHERE FNAME LIKE '%아파트'

-- SQL_02 실습문제 2
USE SOLEMAP
SELECT *
FROM LINK_POI_REL_20251211
WHERE 관할업체 = '티아이랩'

-- SQL_02 실습문제 3 (MCP서버 접속 필수)
USE MCP_DINING
SELECT  * 
FROM MCP_DINING_RAW_20251217
WHERE NAME = '히노아지'
AND branch = '판교파미어스몰점'

-- SQL_03 실습문제 1
USE POI_MAIN_PRACT
SELECT DISTINCT TOP 30 POI_ID, FNAME
FROM vPOI_I_COMMON_ALL_GRS
WHERE FNAME = '현대/블루/핸즈'
AND IFLOOR IS NULL
ORDER BY POI_ID

-- SQL_03 실습문제 2
USE POI_MAIN_PRACT
SELECT DISTINCT TOP 30 POI_ID, FNAME
FROM vPOI_I_COMMON_ALL_GRS
WHERE FNAME = '하나로/마트'
AND IFLOOR IS NOT NULL
ORDER BY POI_ID DESC

-- SQL_03 실습문제 2
USE SOLEMAP
SELECT TOP 10 * 
FROM LINK_POI_REL_20251212
WHERE ADDRESS LIKE '%충주시%'
ORDER BY JIBUN_M ASC, JIBUN_S DESC

-- SQL_04 실습문제 1
USE POI_MAIN_PRACT
SELECT A.POI_ID, A.FNAME, A.CNAME, B.CONSTRUCT_DATE, B.MEMO
FROM vPOI_I_COMMON_ALL_GRS A, PTN_CONSTRUCT B
WHERE A.POI_ID = B.POI_ID
AND B.CONSTRUCT_DATE < '2026-01-16 00:00:00.000'

-- SQL_04 실습문제 2
USE POI_MAIN_PRACT
SELECT B.MAP_ID, A.POI_ID, A.FNAME, A.CNAME, A.ADDR, A.SAN_BUN, A.PRIMARY_BUN, A.SECONDARY_BUN, A.CENTER_X1, A.CENTER_Y1
FROM vPOI_I_COMMON_ALL_GRS A, POI_MAIN_ETC..[22y_2150_INDEX_220401] B
WHERE LEFT(A.TILE_ID,4) = B.MAP_ID
AND B.MAP_ID IN (5528,5616)

-- SQL_04 실습문제 3
USE POI_MAIN_PRACT
SELECT A.POI_ID, A.FNAME, A.CNAME, B.WEEKDAY, B.ST_HOUR, B.ST_MIN, B.ED_HOUR, B.ED_MIN, C.DATE
FROM vPOI_I_COMMON_ALL_GRS A, PTN_WORK_HOUR_REGULAR B, PTN_OFFDAY_DATE C
WHERE A.POI_ID = B.POI_ID
AND A.POI_ID = C.POI_ID
AND C.DATE > '2025-12-07 00:00:00.000'
AND A.POI_ID IN (9561942, 9591647, 9592058)